apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alerts
  namespace: monitoring
spec:
  groups:
  - name: test-alerts
    rules:
    - alert: TestAlert
      expr: up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Test Alert"
        description: "This is a test alert to check Slack notifications."
